### ISSUE TITLE
Fetch new content without server restart?

### ISSUE THREAD

**Issue by simonhermann** [storyblok/storyblok-gridsome-boilerplate#1]
Hi, 
I just started exploring Gridsome + Storyblok and ran into some questions:
Gridsome only fetches content when starting the dev server. I assume Editor.vue is supposed to solve this with storyblok bridge, but it does not work for me.
Is there a way to get content updates without restarting the local server?

**Comment by emanuelgsouza** [comment]
Hi @simonhermann. Thanks for submitting this issue.

Gridsome is a Static Site Generator, so, the data load in build time. That's the Gridsome design. A similar question has been raised in [this issue](https://github.com/gridsome/gridsome/issues/468). Therefore, the Storyblok data will be load in build time.

The Editor page described in [our tutorial](https://www.storyblok.com/tp/gridsome-multilanguage-website-tutorial#live-preview) will be use to enable live preview in our Storyblok Editor.

The only way to get content updates without restarting the server is to use our bridge, like described in our tutorial, but, this way will not make a new request to our data to Graphql Data Layer, because it will be a request in the client/browser.

**Comment by Chizzah** [comment]
I think you can use webhooks like with Contentful but I'm not sure. Hope it helps.

**Comment by simonhermann** [comment]
I think the new guide solves the issue: https://www.storyblok.com/tp/gridsome-multilanguage-website-tutorial
